### ISSUE TITLE
Binary error

### ISSUE THREAD

**Issue by dwisiswant0** [hahwul/WebHackersWeapons#16]
**Describe the bug**
Binary error because it doesn't match architecture it's running on.

**To Reproduce**

```bash
$ ./add-tool 
bash: ./add-tool: cannot execute binary file: Exec format error
$ ./distribute-readme 
bash: ./distribute-readme: cannot execute binary file: Exec format error
```

ELF
```bash
$ file add-tool
add-tool: Mach-O 64-bit x86_64 executable
```

**Expected behavior**
Works fine when running binaries.

**Screenshots**
_N/A_.

**Desktop (please complete the following information):**
 - OS: `linux-gnu x86_64`

**Additional context**
_N/A_.

**Suggestions**
Should create `Makefile` script to build each file instead of storing a binary file in git.

**Comment by hahwul** [comment]
Hi @dwisiswant0 
The error occurred because it is a binary based on my environment(macos).  You can build and use it using the following method.

```
$ go build add-tool.go
$ go build distribute-readme.go
```

I'll update the guide... :D
