### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Strannik74** [hahwul/WebHackersWeapons#19]
❯ go version
go version go1.14.7 linux/amd64
❯ make contribute
Build add-tool 266c944
GOPATH=
go build -ldflags "-w -X github.com/hahwul/WebHackersWeapons/version.GitCommit=266c9444e3e1a3aa0c72285a20ac81b9d6b4bed5+CHANGES -X github.com/hahwul/WebHackersWeapons/version.Version=266c944 -X github.com/hahwul/WebHackersWeapons/version.BuildDate=2020-08-25-16:18:53" -o ./add-tool ./add-tool.go
add-tool.go:8:2: cannot find package "golang.org/x/net/html" in any of:
	/usr/lib/go-1.14/src/golang.org/x/net/html (from $GOROOT)
	/root/go/src/golang.org/x/net/html (from $GOPATH)
make: *** [Makefile:30: add-tool] Ошибка 1

**Comment by hahwul** [comment]
Hi @Strannik74 ,
Thank you for your question! 

I think, the problem seems to be caused by the absence of net/html. 
Does it happen the same after executing the command below?

```
$ go get golang.org/x/net/html
```

**Comment by Strannik74** [comment]
Thank!
Everything is working
