### ISSUE TITLE
ffuf added

### ISSUE THREAD

**Issue by six2dez** [hahwul/WebHackersWeapons#2]
Added ffuf to data.json and uploaded data.json as txt cuz GitHub doesn't support json files

[data.json.txt](https://github.com/hahwul/WebHackersWeapons/files/4449953/data.json.txt)

**Comment by hahwul** [comment]
@six2dez 
Thank you for your Contribute. I added ffuzz. (commit  95a4d42)

![1414](https://user-images.githubusercontent.com/13212227/78783848-3f023a80-79df-11ea-85b6-3baef750d15f.png)
