### ISSUE TITLE
Improve structure

### ISSUE THREAD

**Issue by hahwul** [hahwul/WebHackersWeapons#36]

**Comment by marcus-d19840604** [comment]
> 
_

**Comment by hahwul** [comment]
## Format
### Format
```
Army-Knife/SCAN => 
{
  "type":"army-knife",
  "category":"scanner"
}
```

### Types
* army-knife
* recon
* fuzz
* util

### Categories

**Comment by hahwul** [comment]
## Weapons
### ⚔️ Army-Knife
blahblah

### 🕵️ Recon
blahblah

### 🔥 Fuzzer
blahblah
