### ISSUE TITLE
Submit to the WEB tools list 

### ISSUE THREAD

**Issue by v8blink** [hahwul/WebHackersWeapons#39]
Name: Cyclops
Type:Discovery/XSS
Description: The Cyclops is a web browser with XSS detection feature, it is chromium-based xss detection that used to find the flows from a source to a sink.
github:https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking/blob/main/README-en.md

**Comment by hahwul** [comment]
@v8blink 
I added it! Thank you so much for your contribution :D

**Comment by hahwul** [comment]
@v8blink 
I added it by the basic logic of the whw tool(add-tool), but if you want to change the description, etc., please modify the data.json and send PR it.

https://github.com/hahwul/WebHackersWeapons/blob/main/data.json#L226

**Comment by v8blink** [comment]
Ok, thank you very much. I will PR data.json soon
