### ISSUE TITLE
bash: ./add-tool: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by mehedi1194** [hahwul/WebHackersWeapons#8]
Not machine with my arcitecture 
Any Solution

**Comment by hahwul** [comment]
@mehedi1194 
Ah, the uploaded binary is based on MacOS because I made it for easy use. `go build add-tool.go` to create a binary for your architecture.

```
$ go build add-tool.go
$ ./add-tool -url ~~~~
```

distribution-readme is the same!

**Comment by mehedi1194** [comment]
You are so helpful
Thanks
